package interfacecase

type ServiceGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	ApiMenuService
	InterfaceTemplateService
	ApiConfigService
	TestCaseService
	RunCaseService
	ReportService
	TimerTaskService
	// Code generated by server End; DO NOT EDIT.
}
