{
 "title": "YangfanforDistributedLoadTesting",
 "description": "YangfanforDistributedLoadTesting",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "report", "label": "reportname", "query": { "query": "label_values(report)" } }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(users{mode=\"worker\",report=\"$report\"})"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(users{mode=\"worker\",report=\"$report\"})"
    }
   ]
  },
  {
   "title": "TotalRPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_rps{mode=\"worker\",report=\"$report\"})"
    }
   ]
  },
  {
   "title": "TotalFailRatio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_failures{mode=\"worker\",report=\"$report\",method!~\"transation|testcase\"})/sum(total_num_requests{mode=\"worker\",report=\"$report\",method!~\"transation|testcase\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "TotalFailsPerSecond",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(total_fail_per_sec{mode=\"worker\",report=\"$report\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "TotalRequests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_num_requests{mode=\"worker\",report=\"$report\",method!~\"transaction|testcase\"})"
    }
   ]
  },
  {
   "title": "TotalFailures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_num_failures{mode=\"worker\",report=\"$report\",method!~\"transaction|testcsae\"})"
    }
   ]
  },
  {
   "title": "TotalResponseTimes(PCT95/PCT50)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(response_time{mode=\"worker\",report=\"$report\",quantile=\"0.95\",method!~\"transaction|testcase\"})by(name,method)",
     "legendFormat": "{{method}}-{{name}}PCT95"
    },
    {
     "expr": "avg(response_time{mode=\"worker\",report=\"$report\",quantile=\"0.5\",method!~\"transaction|testcase\"})by(name,method)",
     "legendFormat": "{{method}}-{{name}}PCT50"
    }
   ]
  },
  {
   "title": "TotalResponseTimes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "total_max_response_time{name!~\"Total\",mode=\"worker\",report=\"$report\",method!~\"transaction|testcase\"}",
     "legendFormat": "{{method}}-{{name}}MAX"
    },
    {
     "expr": "total_min_response_time{name!~\"Total\",mode=\"worker\",report=\"$report\",method!~\"transaction|testcase\"}",
     "legendFormat": "{{method}}-{{name}}MIN"
    },
    {
     "expr": "response_time_sum{mode=\"worker\",report=\"$report\",method!=\"transaction\"}/response_time_count{mode=\"standalone\",method!~\"transaction|testcase\"}",
     "legendFormat": "{{method}}-{{name}}AVG"
    },
    {
     "expr": "response_time{quantile=\"0.5\",mode=\"worker\",report=\"$report\",method!~\"transaction|testcase\"}",
     "legendFormat": "{{method}}-{{name}}MEDIAN"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(errors{mode=\"worker\",report=\"$report\"})by(method,name,error)"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "min(min_response_time{mode=\"worker\",report=\"$report\"})by(method,name)"
    },
    {
     "expr": "max(max_response_time{mode=\"worker\",report=\"$report\"})by(method,name)"
    },
    {
     "expr": "avg(average_response_time{mode=\"worker\",report=\"$report\"})by(method,name)"
    },
    {
     "expr": "avg(median_response_time{mode=\"worker\",report=\"$report\"})by(method,name)"
    },
    {
     "expr": "sum(current_rps{mode=\"worker\",report=\"$report\"})by(method,name)"
    },
    {
     "expr": "sum(num_failures{mode=\"worker\",report=\"$report\"})by(method,name)"
    },
    {
     "expr": "sum(num_requests{mode=\"worker\",report=\"$report\"})by(method,name)"
    },
    {
     "expr": "sum(num_failures{mode=\"worker\",report=\"$report\"})by(method,name)/sum(num_requests{mode=\"worker\",report=\"$report\"})by(method,name)"
    }
   ]
  },
  {
   "title": "ResponseTimes(3s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(max_response_time{mode=\"worker\",report=\"$report\",method!~\"transaction|testcase\"})",
     "legendFormat": "{{method}}-{{name}}MAX"
    },
    {
     "expr": "min(min_response_time{mode=\"worker\",report=\"$report\",method!~\"transaction|testcase\"})",
     "legendFormat": "{{method}}-{{name}}MIN"
    },
    {
     "expr": "avg(average_response_time{mode=\"worker\",report=\"$report\",method!~\"transaction|testcase\"})",
     "legendFormat": "{{method}}-{{name}}AVG"
    },
    {
     "expr": "avg(median_response_time{mode=\"worker\",report=\"$report\",method!~\"transaction|testcase\"})",
     "legendFormat": "{{method}}-{{name}}MEDIAN"
    }
   ]
  },
  {
   "title": "RequestsPerEndpoint/s(3s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(current_rps{mode=\"worker\",report=\"$report\",method!~\"transaction|testcase\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "FailsPerEndpoint/s(3s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(num_failures{mode=\"worker\",report=\"$report\",method!~\"transaction|testcase\"})/sum(num_requests{mode=\"worker\",report=\"$report\",method!~\"transaction|testcase\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Transations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_requests{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(total_num_requests{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"})by(name)",
     "legendFormat": "{{method}}-{{name}}"
    }
   ]
  },
  {
   "title": "TransationsPassed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_requests{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"}-total_num_failures{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(total_num_requests{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"})by(name,method)-sum(total_num_failures{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"})by(name,method)",
     "legendFormat": "{{method}}-{{name}}"
    }
   ]
  },
  {
   "title": "TransationsSuccessRate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(total_num_requests{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"}-total_num_failures{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"})/sum(total_num_requests{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"})",
     "legendFormat": "total"
    },
    {
     "expr": "(sum(total_num_requests{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"})by(method,name)-sum(total_num_failures{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"})by(method,name))/sum(total_num_requests{mode=\"worker\",report=\"$report\",method=\"transaction\",name!=\"Action\"})by(method,name)",
     "legendFormat": "{{method}}-{{name}}"
    }
   ]
  }
 ]
}
{
 "title": "yangfanfornodestatus",
 "description": "yangfanfornodestatus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "report", "label": "reportname", "query": { "query": "label_values(report)" } }
  ]
 },
 "panels": [
  {
   "title": "numberofworknodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "master_workers{mode=\"stats\",report=\"$report\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "workusercount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "sum(work_user_count{mode=\"stats\",report=\"$report\"})by(ip)",
     "legendFormat": "{{interval}}"
    }
   ]
  },
  {
   "title": "numberofconcurrentusers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "master_target_users{mode=\"stats\",report=\"$report\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "workcpuusage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(work_cpu_usage{mode=\"stats\",report=\"$report\"})by(ip)",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "workmemoryusage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(work_memory_usage{mode=\"stats\",report=\"$report\"})by(ip)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}