apiVersion: v1
kind: PersistentVolume
metadata:
  name: yangfan-prometheus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  hostPath:
    path: /data/prometheus
