apiVersion: apps/v1
kind: Deployment
metadata:
  name: yangfan-master
  namespace: yangfan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yangfan-master
  template:
    metadata:
      labels:
        app: yangfan-master
    spec:
      containers:
        - name: yangfan-master
          image: registry.cn-hangzhou.aliyuncs.com/yangfanz/master:latest
          ports:
            - containerPort: 7966
              protocol: TCP
            - containerPort: 9093
              protocol: TCP
            - containerPort: 9092
              protocol: TCP
          volumeMounts:
            - name: docker-config-yaml
              mountPath: /yangfan/docker.config.yaml
              subPath: docker.config.yaml
      volumes:
        - name: docker-config-yaml
          configMap:
            name: docker-config-yaml