apiVersion: v1
kind: Service
metadata:
  name: yangfan-server
  namespace: yangfan
spec:
  selector:
    app: yangfan-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      name: http
    - protocol: TCP
      port: 7967
      targetPort: 7967
      name: grpc
  type: ClusterIP