package interfacecase

type RouterGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	ApiMenuRouter
	InterfaceTemplateRouter
	TestCaseRouter

	TimerTaskRouter
	// Code generated by server End; DO NOT EDIT.
}

//type TestCaseRouterRouterGroup struct {
//	TestCaseRouter
//}
type TimerTaskGroup struct {
	TimerTaskRouter
}

type ReportRouterGroup struct {
	ReportRouter
}

type RunCaseRouterGroup struct {
	RunCaseRouter
}

type ApiConfigRouterGroup struct {
	ApiConfigRouter
}
