# NOTE: Generated By hrp v5.0.0-251217, DO NOT EDIT!

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from debugtalk import *


if __name__ == "__main__":
    import funppy
    import inspect

    for name, obj in list(globals().items()):
        if name.startswith("__"):
            continue
        if not inspect.isroutine(obj):
            continue
        funppy.register(name, obj)
    funppy.serve()
