package interfacecase

import "github.com/test-instructor/cheetah/server/service"

type ApiGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	ApiMenuApi
	InterfaceTemplateApi
	ApiCase
	RunCaseApi
	ApiConfigApi
	ReportApi
	ApiCaseApi
	TimerTaskApi
	PerformanceApi
	PyPkg
	// Code generated by server End; DO NOT EDIT.
}

var pyPkgService = service.ServiceGroupApp.InterfacecaseServiceGroup
