package interfacecase

type ApiGroup struct {
	// Code generated by server Begin; DO NOT EDIT.
	ApiMenuApi
	InterfaceTemplateApi
	TestCaseApi
	RunCaseApi
	ApiConfigApi
	ReportApi
	TimerTaskApi
	// Code generated by server End; DO NOT EDIT.
}
