// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.0--rc2
// source: boomer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_OK    Code = 0
	Code_ERROR Code = 1
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Code_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_boomer_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_boomer_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{0}
}

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code   `protobuf:"varint,1,opt,name=Code,proto3,enum=pb.Code" json:"Code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{0}
}

func (x *Resp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

func (x *Resp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpawnCount               int64   `protobuf:"varint,1,opt,name=SpawnCount,proto3" json:"SpawnCount,omitempty"`
	SpawnRate                float64 `protobuf:"fixed64,2,opt,name=SpawnRate,proto3" json:"SpawnRate,omitempty"`
	RunTime                  int64   `protobuf:"varint,3,opt,name=RunTime,proto3" json:"RunTime,omitempty"`
	MaxRPS                   int64   `protobuf:"varint,4,opt,name=MaxRPS,proto3" json:"MaxRPS,omitempty"`
	LoopCount                int64   `protobuf:"varint,5,opt,name=LoopCount,proto3" json:"LoopCount,omitempty"`
	RequestIncreaseRate      string  `protobuf:"bytes,6,opt,name=RequestIncreaseRate,proto3" json:"RequestIncreaseRate,omitempty"`
	MemoryProfile            string  `protobuf:"bytes,7,opt,name=MemoryProfile,proto3" json:"MemoryProfile,omitempty"`
	MemoryProfileDuration    int64   `protobuf:"varint,8,opt,name=MemoryProfileDuration,proto3" json:"MemoryProfileDuration,omitempty"`
	CPUProfile               string  `protobuf:"bytes,9,opt,name=CPUProfile,proto3" json:"CPUProfile,omitempty"`
	CPUProfileDuration       int64   `protobuf:"varint,10,opt,name=CPUProfileDuration,proto3" json:"CPUProfileDuration,omitempty"`
	PrometheusPushgatewayURL string  `protobuf:"bytes,11,opt,name=PrometheusPushgatewayURL,proto3" json:"PrometheusPushgatewayURL,omitempty"`
	DisableConsoleOutput     bool    `protobuf:"varint,12,opt,name=DisableConsoleOutput,proto3" json:"DisableConsoleOutput,omitempty"`
	DisableCompression       bool    `protobuf:"varint,13,opt,name=DisableCompression,proto3" json:"DisableCompression,omitempty"`
	DisableKeepalive         bool    `protobuf:"varint,14,opt,name=DisableKeepalive,proto3" json:"DisableKeepalive,omitempty"`
	ID                       uint64  `protobuf:"varint,15,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *Profile) Reset() {
	*x = Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetSpawnCount() int64 {
	if x != nil {
		return x.SpawnCount
	}
	return 0
}

func (x *Profile) GetSpawnRate() float64 {
	if x != nil {
		return x.SpawnRate
	}
	return 0
}

func (x *Profile) GetRunTime() int64 {
	if x != nil {
		return x.RunTime
	}
	return 0
}

func (x *Profile) GetMaxRPS() int64 {
	if x != nil {
		return x.MaxRPS
	}
	return 0
}

func (x *Profile) GetLoopCount() int64 {
	if x != nil {
		return x.LoopCount
	}
	return 0
}

func (x *Profile) GetRequestIncreaseRate() string {
	if x != nil {
		return x.RequestIncreaseRate
	}
	return ""
}

func (x *Profile) GetMemoryProfile() string {
	if x != nil {
		return x.MemoryProfile
	}
	return ""
}

func (x *Profile) GetMemoryProfileDuration() int64 {
	if x != nil {
		return x.MemoryProfileDuration
	}
	return 0
}

func (x *Profile) GetCPUProfile() string {
	if x != nil {
		return x.CPUProfile
	}
	return ""
}

func (x *Profile) GetCPUProfileDuration() int64 {
	if x != nil {
		return x.CPUProfileDuration
	}
	return 0
}

func (x *Profile) GetPrometheusPushgatewayURL() string {
	if x != nil {
		return x.PrometheusPushgatewayURL
	}
	return ""
}

func (x *Profile) GetDisableConsoleOutput() bool {
	if x != nil {
		return x.DisableConsoleOutput
	}
	return false
}

func (x *Profile) GetDisableCompression() bool {
	if x != nil {
		return x.DisableCompression
	}
	return false
}

func (x *Profile) GetDisableKeepalive() bool {
	if x != nil {
		return x.DisableKeepalive
	}
	return false
}

func (x *Profile) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type StartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *StartReq) Reset() {
	*x = StartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReq) ProtoMessage() {}

func (x *StartReq) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReq.ProtoReflect.Descriptor instead.
func (*StartReq) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{2}
}

func (x *StartReq) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type StartResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *StartResp) Reset() {
	*x = StartResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResp) ProtoMessage() {}

func (x *StartResp) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResp.ProtoReflect.Descriptor instead.
func (*StartResp) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{3}
}

func (x *StartResp) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type RebalanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpawnCount int64   `protobuf:"varint,1,opt,name=SpawnCount,proto3" json:"SpawnCount,omitempty"`
	SpawnRate  float64 `protobuf:"fixed64,2,opt,name=SpawnRate,proto3" json:"SpawnRate,omitempty"`
}

func (x *RebalanceReq) Reset() {
	*x = RebalanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RebalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceReq) ProtoMessage() {}

func (x *RebalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceReq.ProtoReflect.Descriptor instead.
func (*RebalanceReq) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{4}
}

func (x *RebalanceReq) GetSpawnCount() int64 {
	if x != nil {
		return x.SpawnCount
	}
	return 0
}

func (x *RebalanceReq) GetSpawnRate() float64 {
	if x != nil {
		return x.SpawnRate
	}
	return 0
}

type RebalanceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *RebalanceResp) Reset() {
	*x = RebalanceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RebalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceResp) ProtoMessage() {}

func (x *RebalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceResp.ProtoReflect.Descriptor instead.
func (*RebalanceResp) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{5}
}

func (x *RebalanceResp) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type Work struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                string  `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Os                string  `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch              string  `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	State             int32   `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	Heartbeat         int32   `protobuf:"varint,6,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	UserCount         int64   `protobuf:"varint,7,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	WorkerCpuUsage    float64 `protobuf:"fixed64,8,opt,name=worker_cpu_usage,json=workerCpuUsage,proto3" json:"worker_cpu_usage,omitempty"`
	CpuUsage          float64 `protobuf:"fixed64,9,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	CpuWarningEmitted bool    `protobuf:"varint,10,opt,name=cpu_warning_emitted,json=cpuWarningEmitted,proto3" json:"cpu_warning_emitted,omitempty"`
	WorkerMemoryUsage float64 `protobuf:"fixed64,11,opt,name=worker_memory_usage,json=workerMemoryUsage,proto3" json:"worker_memory_usage,omitempty"`
	MemoryUsage       float64 `protobuf:"fixed64,12,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
}

func (x *Work) Reset() {
	*x = Work{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Work) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Work) ProtoMessage() {}

func (x *Work) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Work.ProtoReflect.Descriptor instead.
func (*Work) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{6}
}

func (x *Work) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Work) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Work) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Work) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Work) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Work) GetHeartbeat() int32 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

func (x *Work) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *Work) GetWorkerCpuUsage() float64 {
	if x != nil {
		return x.WorkerCpuUsage
	}
	return 0
}

func (x *Work) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Work) GetCpuWarningEmitted() bool {
	if x != nil {
		return x.CpuWarningEmitted
	}
	return false
}

func (x *Work) GetWorkerMemoryUsage() float64 {
	if x != nil {
		return x.WorkerMemoryUsage
	}
	return 0
}

func (x *Work) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

type WorkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WorkReq) Reset() {
	*x = WorkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkReq) ProtoMessage() {}

func (x *WorkReq) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkReq.ProtoReflect.Descriptor instead.
func (*WorkReq) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{7}
}

type WorkResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Work []*Work `protobuf:"bytes,1,rep,name=work,proto3" json:"work,omitempty"`
}

func (x *WorkResp) Reset() {
	*x = WorkResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResp) ProtoMessage() {}

func (x *WorkResp) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResp.ProtoReflect.Descriptor instead.
func (*WorkResp) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{8}
}

func (x *WorkResp) GetWork() []*Work {
	if x != nil {
		return x.Work
	}
	return nil
}

type MasterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MasterReq) Reset() {
	*x = MasterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterReq) ProtoMessage() {}

func (x *MasterReq) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterReq.ProtoReflect.Descriptor instead.
func (*MasterReq) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{9}
}

type MasterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State        int32 `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
	Workers      int32 `protobuf:"varint,2,opt,name=workers,proto3" json:"workers,omitempty"`
	TargetUsers  int64 `protobuf:"varint,3,opt,name=target_users,json=targetUsers,proto3" json:"target_users,omitempty"`
	CurrentUsers int32 `protobuf:"varint,4,opt,name=current_users,json=currentUsers,proto3" json:"current_users,omitempty"`
}

func (x *MasterResp) Reset() {
	*x = MasterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterResp) ProtoMessage() {}

func (x *MasterResp) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterResp.ProtoReflect.Descriptor instead.
func (*MasterResp) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{10}
}

func (x *MasterResp) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *MasterResp) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *MasterResp) GetTargetUsers() int64 {
	if x != nil {
		return x.TargetUsers
	}
	return 0
}

func (x *MasterResp) GetCurrentUsers() int32 {
	if x != nil {
		return x.CurrentUsers
	}
	return 0
}

type StopReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopReq) Reset() {
	*x = StopReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopReq) ProtoMessage() {}

func (x *StopReq) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopReq.ProtoReflect.Descriptor instead.
func (*StopReq) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{11}
}

type StopResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *StopResp) Reset() {
	*x = StopResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResp) ProtoMessage() {}

func (x *StopResp) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResp.ProtoReflect.Descriptor instead.
func (*StopResp) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{12}
}

func (x *StopResp) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type QuitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuitReq) Reset() {
	*x = QuitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitReq) ProtoMessage() {}

func (x *QuitReq) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitReq.ProtoReflect.Descriptor instead.
func (*QuitReq) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{13}
}

type QuitResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp *Resp `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *QuitResp) Reset() {
	*x = QuitResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boomer_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitResp) ProtoMessage() {}

func (x *QuitResp) ProtoReflect() protoreflect.Message {
	mi := &file_boomer_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitResp.ProtoReflect.Descriptor instead.
func (*QuitResp) Descriptor() ([]byte, []int) {
	return file_boomer_proto_rawDescGZIP(), []int{14}
}

func (x *QuitResp) GetResp() *Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

var File_boomer_proto protoreflect.FileDescriptor

var file_boomer_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x6f, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x3e, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x63, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0xd1, 0x04, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x09, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x52,
	0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x78, 0x52, 0x50, 0x53,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4d, 0x61, 0x78, 0x52, 0x50, 0x53, 0x12, 0x1c,
	0x0a, 0x09, 0x4c, 0x6f, 0x6f, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x4c, 0x6f, 0x6f, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x13,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x52,
	0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x24,
	0x0a, 0x0d, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x15, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x15, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x50,
	0x55, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x43, 0x50, 0x55, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x43, 0x50,
	0x55, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x43, 0x50, 0x55, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x18, 0x50, 0x72,
	0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x50, 0x75, 0x73, 0x68, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x55, 0x52, 0x4c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x50, 0x72,
	0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75, 0x73, 0x50, 0x75, 0x73, 0x68, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x55, 0x52, 0x4c, 0x12, 0x32, 0x0a, 0x14, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x43,
	0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x65,
	0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x22, 0x31, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x25, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x29, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x52, 0x04,
	0x72, 0x65, 0x73, 0x70, 0x22, 0x4c, 0x0a, 0x0c, 0x72, 0x65, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x61,
	0x74, 0x65, 0x22, 0x2d, 0x0a, 0x0d, 0x72, 0x65, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x52, 0x04, 0x72, 0x65, 0x73,
	0x70, 0x22, 0xe7, 0x02, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72,
	0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x28, 0x0a, 0x10, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x63, 0x70, 0x75, 0x5f,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x43, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x70, 0x75, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x63, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x70, 0x75, 0x5f,
	0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x63, 0x70, 0x75, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x45, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x55, 0x73, 0x61, 0x67, 0x65, 0x22, 0x09, 0x0a, 0x07, 0x77,
	0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x22, 0x28, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1c, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x6b,
	0x22, 0x0b, 0x0a, 0x09, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x84, 0x01,
	0x0a, 0x0a, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x22, 0x09, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x22,
	0x28, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x04, 0x72,
	0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x72,
	0x65, 0x73, 0x70, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22, 0x09, 0x0a, 0x07, 0x71, 0x75, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x22, 0x28, 0x0a, 0x08, 0x71, 0x75, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1c, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x70, 0x62, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x2a, 0x19,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x32, 0x81, 0x02, 0x0a, 0x09, 0x62, 0x6f,
	0x6f, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x32, 0x0a, 0x09, 0x72, 0x65, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x2e, 0x70,
	0x62, 0x2e, 0x72, 0x65, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x72, 0x65, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x06, 0x6d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x12, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x73, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x74,
	0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x74,
	0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x71, 0x75, 0x69, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x71, 0x75, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x07, 0x5a,
	0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_boomer_proto_rawDescOnce sync.Once
	file_boomer_proto_rawDescData = file_boomer_proto_rawDesc
)

func file_boomer_proto_rawDescGZIP() []byte {
	file_boomer_proto_rawDescOnce.Do(func() {
		file_boomer_proto_rawDescData = protoimpl.X.CompressGZIP(file_boomer_proto_rawDescData)
	})
	return file_boomer_proto_rawDescData
}

var file_boomer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_boomer_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_boomer_proto_goTypes = []interface{}{
	(Code)(0),             // 0: pb.code
	(*Resp)(nil),          // 1: pb.resp
	(*Profile)(nil),       // 2: pb.profile
	(*StartReq)(nil),      // 3: pb.startReq
	(*StartResp)(nil),     // 4: pb.startResp
	(*RebalanceReq)(nil),  // 5: pb.rebalanceReq
	(*RebalanceResp)(nil), // 6: pb.rebalanceResp
	(*Work)(nil),          // 7: pb.work
	(*WorkReq)(nil),       // 8: pb.workReq
	(*WorkResp)(nil),      // 9: pb.workResp
	(*MasterReq)(nil),     // 10: pb.masterReq
	(*MasterResp)(nil),    // 11: pb.masterResp
	(*StopReq)(nil),       // 12: pb.stopReq
	(*StopResp)(nil),      // 13: pb.stopResp
	(*QuitReq)(nil),       // 14: pb.quitReq
	(*QuitResp)(nil),      // 15: pb.quitResp
}
var file_boomer_proto_depIdxs = []int32{
	0,  // 0: pb.resp.Code:type_name -> pb.code
	2,  // 1: pb.startReq.profile:type_name -> pb.profile
	1,  // 2: pb.startResp.resp:type_name -> pb.resp
	1,  // 3: pb.rebalanceResp.resp:type_name -> pb.resp
	7,  // 4: pb.workResp.work:type_name -> pb.work
	1,  // 5: pb.stopResp.resp:type_name -> pb.resp
	1,  // 6: pb.quitResp.resp:type_name -> pb.resp
	3,  // 7: pb.boomerSer.start:input_type -> pb.startReq
	5,  // 8: pb.boomerSer.rebalance:input_type -> pb.rebalanceReq
	8,  // 9: pb.boomerSer.work:input_type -> pb.workReq
	10, // 10: pb.boomerSer.master:input_type -> pb.masterReq
	12, // 11: pb.boomerSer.stop:input_type -> pb.stopReq
	14, // 12: pb.boomerSer.Quit:input_type -> pb.quitReq
	4,  // 13: pb.boomerSer.start:output_type -> pb.startResp
	6,  // 14: pb.boomerSer.rebalance:output_type -> pb.rebalanceResp
	9,  // 15: pb.boomerSer.work:output_type -> pb.workResp
	11, // 16: pb.boomerSer.master:output_type -> pb.masterResp
	13, // 17: pb.boomerSer.stop:output_type -> pb.stopResp
	15, // 18: pb.boomerSer.Quit:output_type -> pb.quitResp
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_boomer_proto_init() }
func file_boomer_proto_init() {
	if File_boomer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_boomer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RebalanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RebalanceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Work); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boomer_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_boomer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boomer_proto_goTypes,
		DependencyIndexes: file_boomer_proto_depIdxs,
		EnumInfos:         file_boomer_proto_enumTypes,
		MessageInfos:      file_boomer_proto_msgTypes,
	}.Build()
	File_boomer_proto = out.File
	file_boomer_proto_rawDesc = nil
	file_boomer_proto_goTypes = nil
	file_boomer_proto_depIdxs = nil
}
