apiVersion: v1
kind: Service
metadata:
  name: yangfan-grpcdemo
spec:
  selector:
    app: yangfan-grpcdemo
  ports:
    - protocol: TCP
      port: 7967
      targetPort: 7967
      nodePort: 31067
  type: NodePort
