{
 "title": "yangfan for node status",
 "description": "yangfan for node status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "report", "label": "report name", "query": { "query": "label_values(report)" } }
  ]
 },
 "panels": [
  {
   "title": "number of work nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "master_workers{mode=\"stats\",report=\"$report\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "work user count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "sum(work_user_count{mode=\"stats\", report=\"$report\"}) by (ip)",
     "legendFormat": "{{interval}}"
    }
   ]
  },
  {
   "title": "number of concurrent users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "master_target_users{mode=\"stats\",report=\"$report\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "work cpu usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(work_cpu_usage{mode=\"stats\", report=\"$report\"}) by (ip)",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "work memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(work_memory_usage{mode=\"stats\", report=\"$report\"}) by (ip)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}