// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Captcha() {
  return window['go']['main']['App']['Captcha']();
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function ClearAuth() {
  return window['go']['main']['App']['ClearAuth']();
}

export function GetBaseURL() {
  return window['go']['main']['App']['GetBaseURL']();
}

export function GetLogConfig() {
  return window['go']['main']['App']['GetLogConfig']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasToken() {
  return window['go']['main']['App']['HasToken']();
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3, arg4);
}

export function RunTestCase(arg1) {
  return window['go']['main']['App']['RunTestCase'](arg1);
}

export function SetBaseURL(arg1) {
  return window['go']['main']['App']['SetBaseURL'](arg1);
}

export function SetLogConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetLogConfig'](arg1, arg2, arg3);
}

export function SetSelfInfo(arg1) {
  return window['go']['main']['App']['SetSelfInfo'](arg1);
}

export function SetUserAuthority(arg1, arg2) {
  return window['go']['main']['App']['SetUserAuthority'](arg1, arg2);
}
