// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAutoCaseStep(arg1:number,arg2:number):Promise<void>;

export function AddAutoCaseStepApi(arg1:number,arg2:number,arg3:number):Promise<Record<string, any>>;

export function AddTimerTaskCase(arg1:number,arg2:number):Promise<void>;

export function Captcha():Promise<Record<string, any>>;

export function ChangePassword(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CheckBaseURLConnectivity(arg1:string):Promise<Record<string, any>>;

export function ClearAuth():Promise<void>;

export function CreateAndroidDeviceOptions(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateAutoCase(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateAutoCaseStep(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateAutoStep(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateRunConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateTimerTask(arg1:Record<string, any>):Promise<Record<string, any>>;

export function DeleteAndroidDeviceOptions(arg1:number):Promise<void>;

export function DeleteAutoCase(arg1:number):Promise<void>;

export function DeleteAutoCaseStep(arg1:number):Promise<void>;

export function DeleteAutoCaseStepApi(arg1:number):Promise<void>;

export function DeleteAutoCaseStepRef(arg1:number):Promise<void>;

export function DeleteAutoStep(arg1:number):Promise<void>;

export function DeleteRunConfig(arg1:number):Promise<void>;

export function DeleteTimerTask(arg1:number):Promise<void>;

export function DeleteTimerTaskCaseRef(arg1:number):Promise<void>;

export function FindAutoCaseStepApis(arg1:number):Promise<Array<Record<string, any>>>;

export function FindAutoReport(arg1:number):Promise<Record<string, any>>;

export function GetAndroidDeviceOptionsList(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetAppConfig():Promise<Record<string, any>>;

export function GetAutoCaseList(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetAutoCaseStepList(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetAutoCaseSteps(arg1:number):Promise<Array<Record<string, any>>>;

export function GetAutoReportList(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetAutoStepList(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetBaseURL():Promise<string|boolean>;

export function GetLogConfig():Promise<Record<string, any>>;

export function GetRunConfigList(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetTimerTaskCases(arg1:number):Promise<Array<Record<string, any>>>;

export function GetTimerTaskList(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetUINodeMenuTree():Promise<Array<Record<string, any>>>;

export function GetUserInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function HasToken():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function RunTestCase(arg1:string):Promise<string>;

export function SetAppConfig(arg1:string,arg2:boolean,arg3:string,arg4:string,arg5:boolean,arg6:boolean):Promise<void>;

export function SetAutoCaseStepConfig(arg1:number,arg2:boolean,arg3:boolean):Promise<void>;

export function SetBaseURL(arg1:string):Promise<void>;

export function SetLogConfig(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetSelfInfo(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SetUserAuthority(arg1:number,arg2:number):Promise<Record<string, any>>;

export function SortAutoCaseStepApis(arg1:Array<Record<string, any>>):Promise<void>;

export function SortAutoCaseSteps(arg1:number,arg2:Array<Record<string, any>>):Promise<void>;

export function SortTimerTaskCases(arg1:number,arg2:Array<Record<string, any>>):Promise<void>;

export function TrackError(arg1:Record<string, any>):Promise<void>;

export function TrackPerformance(arg1:Record<string, any>):Promise<void>;

export function UpdateAndroidDeviceOptions(arg1:Record<string, any>):Promise<Record<string, any>>;

export function UpdateAutoCase(arg1:Record<string, any>):Promise<Record<string, any>>;

export function UpdateAutoCaseStep(arg1:Record<string, any>):Promise<Record<string, any>>;

export function UpdateAutoStep(arg1:Record<string, any>):Promise<Record<string, any>>;

export function UpdateRunConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function UpdateTimerTask(arg1:Record<string, any>):Promise<Record<string, any>>;
