// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAutoCaseStep(arg1, arg2) {
  return window['go']['main']['App']['AddAutoCaseStep'](arg1, arg2);
}

export function AddAutoCaseStepApi(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAutoCaseStepApi'](arg1, arg2, arg3);
}

export function AddTimerTaskCase(arg1, arg2) {
  return window['go']['main']['App']['AddTimerTaskCase'](arg1, arg2);
}

export function Captcha() {
  return window['go']['main']['App']['Captcha']();
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function CheckBaseURLConnectivity(arg1) {
  return window['go']['main']['App']['CheckBaseURLConnectivity'](arg1);
}

export function ClearAuth() {
  return window['go']['main']['App']['ClearAuth']();
}

export function CreateAndroidDeviceOptions(arg1) {
  return window['go']['main']['App']['CreateAndroidDeviceOptions'](arg1);
}

export function CreateAutoCase(arg1) {
  return window['go']['main']['App']['CreateAutoCase'](arg1);
}

export function CreateAutoCaseStep(arg1) {
  return window['go']['main']['App']['CreateAutoCaseStep'](arg1);
}

export function CreateAutoStep(arg1) {
  return window['go']['main']['App']['CreateAutoStep'](arg1);
}

export function CreateRunConfig(arg1) {
  return window['go']['main']['App']['CreateRunConfig'](arg1);
}

export function CreateTimerTask(arg1) {
  return window['go']['main']['App']['CreateTimerTask'](arg1);
}

export function DeleteAndroidDeviceOptions(arg1) {
  return window['go']['main']['App']['DeleteAndroidDeviceOptions'](arg1);
}

export function DeleteAutoCase(arg1) {
  return window['go']['main']['App']['DeleteAutoCase'](arg1);
}

export function DeleteAutoCaseStep(arg1) {
  return window['go']['main']['App']['DeleteAutoCaseStep'](arg1);
}

export function DeleteAutoCaseStepApi(arg1) {
  return window['go']['main']['App']['DeleteAutoCaseStepApi'](arg1);
}

export function DeleteAutoCaseStepRef(arg1) {
  return window['go']['main']['App']['DeleteAutoCaseStepRef'](arg1);
}

export function DeleteAutoStep(arg1) {
  return window['go']['main']['App']['DeleteAutoStep'](arg1);
}

export function DeleteRunConfig(arg1) {
  return window['go']['main']['App']['DeleteRunConfig'](arg1);
}

export function DeleteTimerTask(arg1) {
  return window['go']['main']['App']['DeleteTimerTask'](arg1);
}

export function DeleteTimerTaskCaseRef(arg1) {
  return window['go']['main']['App']['DeleteTimerTaskCaseRef'](arg1);
}

export function FindAutoCaseStepApis(arg1) {
  return window['go']['main']['App']['FindAutoCaseStepApis'](arg1);
}

export function FindAutoReport(arg1) {
  return window['go']['main']['App']['FindAutoReport'](arg1);
}

export function GetAndroidDeviceOptionsList(arg1) {
  return window['go']['main']['App']['GetAndroidDeviceOptionsList'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetAutoCaseList(arg1) {
  return window['go']['main']['App']['GetAutoCaseList'](arg1);
}

export function GetAutoCaseStepList(arg1) {
  return window['go']['main']['App']['GetAutoCaseStepList'](arg1);
}

export function GetAutoCaseSteps(arg1) {
  return window['go']['main']['App']['GetAutoCaseSteps'](arg1);
}

export function GetAutoReportList(arg1) {
  return window['go']['main']['App']['GetAutoReportList'](arg1);
}

export function GetAutoStepList(arg1) {
  return window['go']['main']['App']['GetAutoStepList'](arg1);
}

export function GetBaseURL() {
  return window['go']['main']['App']['GetBaseURL']();
}

export function GetLogConfig() {
  return window['go']['main']['App']['GetLogConfig']();
}

export function GetRunConfigList(arg1) {
  return window['go']['main']['App']['GetRunConfigList'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTimerTaskCases(arg1) {
  return window['go']['main']['App']['GetTimerTaskCases'](arg1);
}

export function GetTimerTaskList(arg1) {
  return window['go']['main']['App']['GetTimerTaskList'](arg1);
}

export function GetUINodeMenuTree() {
  return window['go']['main']['App']['GetUINodeMenuTree']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasToken() {
  return window['go']['main']['App']['HasToken']();
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3, arg4);
}

export function RunTestCase(arg1) {
  return window['go']['main']['App']['RunTestCase'](arg1);
}

export function SetAppConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SetAppConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetAutoCaseStepConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAutoCaseStepConfig'](arg1, arg2, arg3);
}

export function SetBaseURL(arg1) {
  return window['go']['main']['App']['SetBaseURL'](arg1);
}

export function SetLogConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetLogConfig'](arg1, arg2, arg3);
}

export function SetSelfInfo(arg1) {
  return window['go']['main']['App']['SetSelfInfo'](arg1);
}

export function SetUserAuthority(arg1, arg2) {
  return window['go']['main']['App']['SetUserAuthority'](arg1, arg2);
}

export function SortAutoCaseStepApis(arg1) {
  return window['go']['main']['App']['SortAutoCaseStepApis'](arg1);
}

export function SortAutoCaseSteps(arg1, arg2) {
  return window['go']['main']['App']['SortAutoCaseSteps'](arg1, arg2);
}

export function SortTimerTaskCases(arg1, arg2) {
  return window['go']['main']['App']['SortTimerTaskCases'](arg1, arg2);
}

export function TrackError(arg1) {
  return window['go']['main']['App']['TrackError'](arg1);
}

export function TrackPerformance(arg1) {
  return window['go']['main']['App']['TrackPerformance'](arg1);
}

export function UpdateAndroidDeviceOptions(arg1) {
  return window['go']['main']['App']['UpdateAndroidDeviceOptions'](arg1);
}

export function UpdateAutoCase(arg1) {
  return window['go']['main']['App']['UpdateAutoCase'](arg1);
}

export function UpdateAutoCaseStep(arg1) {
  return window['go']['main']['App']['UpdateAutoCaseStep'](arg1);
}

export function UpdateAutoStep(arg1) {
  return window['go']['main']['App']['UpdateAutoStep'](arg1);
}

export function UpdateRunConfig(arg1) {
  return window['go']['main']['App']['UpdateRunConfig'](arg1);
}

export function UpdateTimerTask(arg1) {
  return window['go']['main']['App']['UpdateTimerTask'](arg1);
}
