// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Captcha():Promise<Record<string, any>>;

export function ChangePassword(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CheckBaseURLConnectivity(arg1:string):Promise<Record<string, any>>;

export function ClearAuth():Promise<void>;

export function GetAppConfig():Promise<Record<string, any>>;

export function GetBaseURL():Promise<string|boolean>;

export function GetLogConfig():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetUserInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function HasToken():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function RunTestCase(arg1:string):Promise<string>;

export function SetAppConfig(arg1:string,arg2:boolean,arg3:string,arg4:string,arg5:boolean,arg6:boolean):Promise<void>;

export function SetBaseURL(arg1:string):Promise<void>;

export function SetLogConfig(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetSelfInfo(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SetUserAuthority(arg1:number,arg2:number):Promise<Record<string, any>>;

export function TrackError(arg1:Record<string, any>):Promise<void>;

export function TrackPerformance(arg1:Record<string, any>):Promise<void>;
