// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Captcha():Promise<Record<string, any>>;

export function ClearAuth():Promise<void>;

export function GetBaseURL():Promise<string|boolean>;

export function GetUserInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function HasToken():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function RunTestCase(arg1:string):Promise<string>;

export function SetBaseURL(arg1:string):Promise<void>;

export function SetUserAuthority(arg1:number,arg2:number):Promise<Record<string, any>>;
